server:
  port: 13000

spring:
  application:
    name: eureka-server
  security:
    basic:
      enable: true #开启基于http basic 的认证
    user: #配置用户信息
      name: wzw
      password: 1234

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true #集群为true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:12000/eureka/
  server:
    enable-self-preservation: false #禁用自我保护机制