server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    hikari: #springboot 2.x 默认数据库连接池
      maximum-pool-size: 20 #
      connection-timeout: 60000 #
      idle-timeout: 60000  #
      max-lifetime: 60000  #
      validation-timeout: 3000  #
      login-timeout: 5 #

  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect #数据库方言

  #---------redis----------
  redis:
    database: 1 #redis数据库索引
    host: 192.168.100.101 #redis服务器地址
    port: 6379  #redis 连接端口
    #password:   #redis 默认密码为空
    jedis:
      pool:
        max-active: 200 #连接池的最大连接数（负值标识没有限制 ）
        max-wait: -1 #连接池最大阻塞时间（负值没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接
    timeout: 1000 #连接超时时间ms
