server:
  port: 8843
spring:
  application:
    name: white jotter
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/wj?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      show-sql: true
      hibernate.ddl-auto: update
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

proxy.servlet_url: /*
proxy.target_url: http://api.zhuishushenqi.com