server:
  port: 12002
spring:
  application:
    name: service-consumer

eureka:
  client:
    serviceUrl:
    # 集群配置
      defaultZone: http://wzw:1234@localhost:12000/eureka/,http://wzw:1234@localhost:13000/eureka/
server-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule