
server:
  port: 13001
spring:
  application:
    name: service-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://wzw:1234@localhost:12000/eureka/,http://wzw:1234@localhost:13000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的IP地址注册到eureka服务
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id